# ── JVM ─────────────────────────────────────────────────────────────────────
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# ── AndroidX ─────────────────────────────────────────────────────────────────
android.useAndroidX=true

# ── Kotlin ───────────────────────────────────────────────────────────────────
kotlin.code.style=official

# ── Derleme performansı ──────────────────────────────────────────────────────
org.gradle.parallel=true
org.gradle.caching=true
android.nonTransitiveRClass=true
